### ISSUE TITLE
CORS

### ISSUE THREAD

**Issue by andersondeoliveiramachado** [joaosouz4/express-zapapi#1]
![image](https://user-images.githubusercontent.com/1152426/87232129-05045400-c393-11ea-9de0-829a679a64ee.png)
como posso liberar ?

**Comment by joaosouz4** [comment]
CORS está liberado, confira se seu ip está definido corretamente.

**Comment by andersondeoliveiramachado** [comment]
Eu coloquei o front no web server , e agora abriu , mas ainda com algumas mensagens de CORS.

![image](https://user-images.githubusercontent.com/1152426/87232474-ba380b80-c395-11ea-8bd5-fd69c90c4ff4.png)

**Comment by joaosouz4** [comment]
locahost não vai permitir vc usar o sistema em outro dispositivo
acredito que o cors já está liberado, fiz varios testes referente a isso.

**Comment by andersondeoliveiramachado** [comment]
> locahost não vai permitir vc usar o sistema em outro dispositivo
> acredito que o cors já está liberado, fiz varios testes referente a isso.

Vou tentar colocar em  : http://comunicacao.test/  tanto o server como o front e testar. No momento estou testando na minha maquina.

**Comment by joaosouz4** [comment]
localmente, apenas starto o node e o front eu ligo ele em um servidor simples apache, e mudo o ip para meu ip local, para que eu passa testar em outras maquinas

**Comment by andersondeoliveiramachado** [comment]
> localmente, apenas starto o node e o front eu ligo ele em um servidor simples apache, e mudo o ip para meu ip local, para que eu passa testar em outras maquinas

Foi desta forma que fiz aqui , e funcionou.
